### ISSUE TITLE
해상도 경고창 렌더링 시 기존 정보 초기화

### ISSUE THREAD

**Issue by Ryuna4347** [kwagyoo/42memory#40]
- 상황
브라우저 창크기 경고창(1280x750)이 뜨게 될 시 기존 컴포넌트의 상태가 모두 초기화되어 창을 키웠을 때 기존 상태를 유지하지 못하는 현상이 발생

경고창의 조건이 3항 연산으로 되어있어서 경고창이 뜨게 될시 기존 컴포넌트를 unmount하는게 문제가 되는 것으로 보인다.

**Comment by kwag93** [comment]
#41 수정했음
